name: "(CI) Main Workflow"

on:
  pull_request:

jobs:
  basic-shit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Installing dependencies
        run: yarn install

      - name: Running Lint
        run: yarn lint

      - name: Running Tests
        run: yarn test
